import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'providers/expense_provider.dart';
import 'providers/auth_provider.dart';
import 'providers/user_preferences_provider.dart';
import 'providers/theme_provider.dart';
import 'providers/sync_provider.dart';
import 'providers/recurring_expense_provider.dart';
import 'services/connectivity_monitor.dart';
import 'services/queue_service.dart';
import 'repositories/supabase_expense_repository.dart';
import 'widgets/auth_gate.dart';
import 'theme/minimalist/minimalist_theme.dart';
// Offline Queue - Hive models and adapters
import 'models/scanning/queued_receipt.dart';
import 'models/scanning/queued_item.dart';

// This is the entry point of the Flutter app
// The main() function is called when the app starts
// Now async to support Supabase initialization
Future<void> main() async {
  // Ensure Flutter bindings are initialized before async operations
  // Required for loading .env and initializing Supabase
  WidgetsFlutterBinding.ensureInitialized();

  // Load environment variables from .env file
  // This contains our Supabase URL and Anon Key
  await dotenv.load(fileName: '.env');

  // Initialize Hive for offline queue
  // Hive is a fast, lightweight NoSQL database for Flutter
  // Used for queuing expenses (manual + scanned) when offline
  await Hive.initFlutter();

  // Register Hive adapters for offline queue models
  // These adapters were auto-generated by build_runner
  // They tell Hive how to serialize/deserialize our custom classes
  Hive.registerAdapter(QueuedReceiptAdapter());
  Hive.registerAdapter(QueuedItemAdapter());

  // Open the expense queue box for offline storage
  // Think of a "box" as a table in SQL - it stores QueuedReceipt objects
  // This box persists across app restarts
  await Hive.openBox<QueuedReceipt>('expense_queue');

  // Initialize Supabase with credentials from .env
  // This must complete before the app starts
  await Supabase.initialize(
    url: dotenv.env['SUPABASE_URL']!,
    anonKey: dotenv.env['SUPABASE_ANON_KEY']!,
  );

  // Initialize offline queue services
  final connectivityMonitor = ConnectivityMonitor();
  await connectivityMonitor.initialize();

  final queueService = QueueService();
  await queueService.initialize();

  runApp(ExpenseTrackerApp(
    connectivityMonitor: connectivityMonitor,
    queueService: queueService,
  ));
}

// ExpenseTrackerApp is the root widget of our application
// It's a StatelessWidget because the app-level configuration doesn't change
class ExpenseTrackerApp extends StatelessWidget {
  final ConnectivityMonitor connectivityMonitor;
  final QueueService queueService;

  const ExpenseTrackerApp({
    super.key,
    required this.connectivityMonitor,
    required this.queueService,
  });

  @override
  Widget build(BuildContext context) {
    // MultiProvider allows us to provide multiple providers to the widget tree
    // We now have five providers:
    // 1. AuthProvider - handles user authentication and session
    // 2. ExpenseProvider - manages expense data with offline queue support
    // 3. UserPreferencesProvider - manages user settings and budget configuration
    // 4. ThemeProvider - manages dark/light theme mode and persistence
    // 5. SyncProvider - manages offline queue sync state and auto-sync
    // All providers are available to all descendant widgets
    return MultiProvider(
      providers: [
        // AuthProvider must be first because other providers may depend on auth state
        ChangeNotifierProvider(
          create: (context) => AuthProvider(),
        ),
        // ExpenseProvider handles expense data management with offline queue
        // OPTIMIZATION: Don't call loadExpenses() here - it will be called in
        // MainNavigationScreen after auth state is confirmed. This prevents
        // double loading and ensures we don't query Supabase before auth is ready.
        ChangeNotifierProvider(
          create: (context) {
            return ExpenseProvider(
              connectivityMonitor: connectivityMonitor,
              queueService: queueService,
            );
          },
        ),
        // UserPreferencesProvider handles user settings and budget configuration
        ChangeNotifierProvider(
          create: (context) {
            final provider = UserPreferencesProvider();
            // Load user preferences (budget, language, theme) when provider is created
            // Creates default preferences (20M VND budget) for new users automatically
            provider.loadPreferences();
            return provider;
          },
        ),
        // ThemeProvider manages dark/light/system theme mode
        ChangeNotifierProvider(
          create: (context) => ThemeProvider(),
        ),
        // SyncProvider manages offline queue sync state
        // Automatically syncs when connectivity returns
        ChangeNotifierProvider(
          create: (context) => SyncProvider(
            queueService: queueService,
            connectivityMonitor: connectivityMonitor,
            expenseRepository: SupabaseExpenseRepository(),
          ),
        ),
        // RecurringExpenseProvider manages recurring expense templates
        // Auto-creates monthly expenses when the app opens
        ChangeNotifierProvider(
          create: (context) => RecurringExpenseProvider(),
        ),
      ],
      // Consumer listens to ThemeProvider and rebuilds MaterialApp when theme changes
      child: Consumer<ThemeProvider>(
        builder: (context, themeProvider, child) {
          return MaterialApp(
            // App title (shown in task switcher on Android)
            title: 'Expense Tracker',

            // Disable the debug banner in the top-right corner
            debugShowCheckedModeBanner: false,

            // Use our minimalist theme system with dark mode support
            // MinimalistTheme provides consistent design tokens throughout the app
            theme: MinimalistTheme.lightTheme,
            darkTheme: MinimalistTheme.darkTheme,

            // Use theme mode from ThemeProvider (light/dark/system)
            // User can change this in Settings, and it persists across app restarts
            themeMode: themeProvider.themeMode,

            // Set AuthGate as the home screen (instead of MainNavigationScreen)
            // AuthGate checks authentication and shows:
            // - LoginScreen if not authenticated
            // - MainNavigationScreen if authenticated
            home: const AuthGate(),
          );
        },
      ),
    );
  }
}
