import 'package:hive/hive.dart';

// This will be generated by build_runner
part 'queued_item.g.dart';

/// Hive model for storing individual items in the offline queue
///
/// This is a simplified version of ScannedItem optimized for persistence.
/// When offline, ScannedItems are converted to QueuedItems and stored in Hive.
@HiveType(typeId: 1)
class QueuedItem extends HiveObject {
  /// Description of the item
  @HiveField(0)
  String description;

  /// Amount in VND
  @HiveField(1)
  double amount;

  /// Category name in Vietnamese
  @HiveField(2)
  String categoryNameVi;

  /// Expense type in Vietnamese
  @HiveField(3)
  String typeNameVi;

  /// Date for this expense
  @HiveField(4)
  DateTime date;

  /// Optional note
  @HiveField(5)
  String? note;

  QueuedItem({
    required this.description,
    required this.amount,
    required this.categoryNameVi,
    required this.typeNameVi,
    required this.date,
    this.note,
  });

  /// Convert to JSON for debugging
  Map<String, dynamic> toJson() {
    return {
      'description': description,
      'amount': amount,
      'categoryNameVi': categoryNameVi,
      'typeNameVi': typeNameVi,
      'date': date.toIso8601String(),
      'note': note,
    };
  }

  /// Create from JSON
  factory QueuedItem.fromJson(Map<String, dynamic> json) {
    return QueuedItem(
      description: json['description'] as String,
      amount: (json['amount'] as num).toDouble(),
      categoryNameVi: json['categoryNameVi'] as String,
      typeNameVi: json['typeNameVi'] as String,
      date: DateTime.parse(json['date'] as String),
      note: json['note'] as String?,
    );
  }

  @override
  String toString() {
    return 'QueuedItem(description: $description, amount: $amount, '
        'category: $categoryNameVi, type: $typeNameVi, date: $date)';
  }
}
